goaler/apps/measurement_tracker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /tracker/
    url(r'^$', views.history, name='history'),
    # ex: /tracker/add/
    url(r'^add/', views.add, name='add'),
]

goaler/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import home, home_files

urlpatterns = [
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        home_files, name='home-files'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'}),
    url(r'accounts/', include('allauth.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^$', home, name='home'),
    url(r'^tracker/', include('goaler.apps.measurement_tracker.urls', namespace='measurement_tracker')),
    url(r'^admin/', admin.site.urls),
)

goaler/apps/goaler/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.dispatch import receiver

from . import managers


class UserProfile(models.Model):
    # Relations
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profile',
        verbose_name=_('user'),
    )

    # Attributes - Mandatory
    interaction = models.PositiveIntegerField(
        default=0,
        verbose_name=_('interaction'),
    )

    # Attributes - Optional
    date_of_birth = models.DateField(
        null=True,
        verbose_name=_('date of birth'),
    )

    sex = models.CharField(
        null=True,
        max_length=1,
        choices=(('M', 'Male'), ('F', 'Female')),
        verbose_name=_('sex'),
    )

    # Object Manager
    objects = managers.UserProfileManager()

    # Custom Properties
    @property
    def username(self):
        return self.user.username

    # Methods

    # Meta and String
    class Meta:
        verbose_name = _('User Profile')
        verbose_name_plural = _('User Profiles')
        ordering = ('user',)

        def __str__(self):
            return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile_for_new_user(sender, created, instance, **kwargs):
    if created:
        profile = UserProfile(user=instance)
        profile.save()

goaler/apps/measurement_tracker/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from . import managers


class Measurement(models.Model):
    # Relations
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='measurements',
        verbose_name=_('user'),
    )

    # Attributes - Mandatory
    weight = models.FloatField(
        validators=[MinValueValidator(0.0)],
        verbose_name=_('weight'),
        help_text=_('Enter your body weight'),
    )

    date = models.DateField(
        verbose_name=_('date'),
        default=timezone.now,
    )

    # Attributes - Optional
    neck = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('neck'),
        help_text=('Enter your neck circumference'),
    )

    chest = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('chest'),
        help_text=('Enter your chest circumference'),
    )

    arm = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('arm'),
        help_text=('Enter your arm circumference'),
    )

    waist = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('waist'),
        help_text=('Enter your waist circumference'),
    )

    hip = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('hip'),
        help_text=('Enter your hip circumference'),
    )

    thigh = models.FloatField(
        null=True,
        validators=[MinValueValidator(0.0)],
        verbose_name=('thigh'),
        help_text=('Enter your thigh circumference'),
    )

    # Object Manager
    objects = managers.MeasurementManager()

    # Custom Properties

    # Methods

    # Meta and String
    class Meta:
        verbose_name = _('Measurement')
        verbose_name_plural = _('Measurements')
        ordering = ('user', 'date')
        # unique_together = ('user', 'date')

    def __str__(self):
        return '{}kg'.format(self.weight)

goaler/apps/measurement_tracker/forms.py
from django import forms

from .models import Measurement


class MeasurementForm(forms.ModelForm):

    neck = forms.FloatField(required=False)
    chest = forms.FloatField(required=False)
    arm = forms.FloatField(required=False)
    waist = forms.FloatField(required=False)
    hip = forms.FloatField(required=False)
    thigh = forms.FloatField(required=False)

    class Meta:
        model = Measurement
        exclude = ['user', 'date']

goaler/apps/goaler/views.py
from django.shortcuts import render

# Create your views here.

goaler/apps/measurement_tracker/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import loader
from django.utils import timezone

from .forms import MeasurementForm
from .models import Measurement


@login_required
def history(request):
    latest_measurements = Measurement.objects.filter(user=request.user).order_by('-date')[:30]

    types = ['weight', 'neck', 'chest', 'arm', 'waist', 'hip', 'thigh']
    colors = ['#990000', '#999900', '#009900', '#990099', '#000099', '#660099', '#996600']
    datasets = []

    dates = [date[0].isoformat() for date in list(latest_measurements.values_list('date'))]

    for i, t in enumerate(types):
        measurements = [m[0] for m in list(latest_measurements.values_list(t))]
        data_points = [{'x': dates[i], 'y': measurements[i]} for i in reversed(range(len(measurements)))]
        datasets.append({
            'label': t.title(),
            'data': data_points,
            'lineTension': 0,
            'borderColor': colors[i],
            'backgroundColor': colors[i],
            'fill': False,
        })

    labels = [date[0].strftime('%Y/%m/%d') for date in list(latest_measurements.values_list('date'))]
    labels = list(set(labels))

    data = {
        'labels': labels,
        'datasets': datasets
    }

    options = {
        'responsive': True,
        'title': {
            'display': True,
            'text': 'Measurement History',
        },
        'tooltips': {
            'mode': 'index',
            'intersect': False,
        },
        'hover': {
            'mode': 'nearest',
            'intersect': True,
        },
        'scales': {
            'xAxes': [{
                'display': True,
                'scaleLabel': {
                    'display': True,
                    'labelString': 'Date',
                },
            }],
            'yAxes': [{
                'display': True,
                'scaleLabel': {
                    'display': True,
                    'labelString': 'Weight | Circumference',
                }
            }],
        }
    }

    data = json.dumps(data)
    options = json.dumps(options)

    template = loader.get_template('measurement_tracker/history.html')
    context = {
        'latest_measurements': latest_measurements,
        'chart_data': data,
        'chart_options': options,
    }

    return HttpResponse(template.render(context, request))


@login_required
def add(request):
    if request.method == 'POST':
        form = MeasurementForm(request.POST)

        if form.is_valid():
            measurement = form.save(commit=False)
            measurement.user = request.user
            measurement.date = timezone.now()
            measurement.save()

            return redirect('measurement_tracker:history')
    template = loader.get_template('measurement_tracker/add.html')
    context = {
        'today': timezone.now().date,
        'form': MeasurementForm(),
    }

    return HttpResponse(template.render(context, request))

goaler/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def home(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('measurement_tracker:history'))
    else:
        return render(request, 'goaler/index.html')


def home_files(request, filename):
    return render(request, filename, {}, content_type='text/plain')

goaler/apps/measurement_tracker/templates/measurement_tracker/add.html
{%  extends 'base.html' %}

{% block content %}
    <h1>Record a Measurement for {{ today }}</h1>

    {% if error_message %}<div class="alert alert-danger"><strong>{{ error_message }}</strong></div>{% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Track</button>
    </form>
{% endblock %}

goaler/apps/measurement_tracker/templates/measurement_tracker/history.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block head_javascript %}
    <script src="{% static 'chart.js/dist/Chart.bundle.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>{% trans 'Measurement History' %}</h1>
    {% if latest_measurements %}
        {% blocktrans %}
            <p>This is your measurement history. Here you can see the past 30 measurements that you have recorded and a
                graph representing them. This is a great place to take a look at your progress!</p>
            <p>TIP: Click on the line labels above the graph to disable and enable lines!</p>
        {%  endblocktrans %}

        <canvas id="measurementHistoryChart"></canvas>
        <script>
            var data = {{ chart_data|safe }}
            var options = {{ chart_options|safe }}
            var ctx = document.getElementById('measurementHistoryChart').getContext('2d');
            var measurementHistoryChart = new Chart(ctx, {
                type: 'line',
                data: data,
                options: options
            });
        </script>
        <table class="table table-striped table-responsive">
            <tr>
                <th>Date</th>
                <th>Weight</th>
                <th>Neck</th>
                <th>Chest</th>
                <th>Arm</th>
                <th>Waist</th>
                <th>Hip</th>
                <th>Thigh</th>
            </tr>
            {% for measurement in latest_measurements %}
                <tr>
                    <td>{{ measurement.date }}</td>
                    <td>{{ measurement.weight }}</td>
                    <td>{{ measurement.neck }}</td>
                    <td>{{ measurement.chest }}</td>
                    <td>{{ measurement.arm }}</td>
                    <td>{{ measurement.waist }}</td>
                    <td>{{ measurement.hip }}</td>
                    <td>{{ measurement.thigh }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No measurement history. Click add and get tracking!</p>
    {% endif %}
    <a id="track" href="{% url 'measurement_tracker:add' %}" class="btn btn-success">Add New Measurement</a>
{% endblock %}

goaler/templates/base.html
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    {% block head_css %}{% endblock %}
    {% block head_javascript %}{% endblock %}
</head>
<body>
<!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
{% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Goaler</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div class="navbar-form navbar-right">
                    {% if user.is_authenticated %}
                        <div class="row-fluid">
                            <div class="dropdown" style="display: inline-block;">
                                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Tools
                                <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a id="measurements" href="{% url 'measurement_tracker:history' %}">Measurements</a>
                                    </li>
                                </ul>
                            </div>
                            <a id="google_logout" href="/accounts/logout" class="btn btn-default" display="inline-block">Logout</a>
                        </div>
                    {% else %}
                        <a id="google_login" href="/accounts/google/login" class="btn btn-default">
                            Sign in with Google
                        </a>
                    {% endif %}
                </div>
            </div><!--/.navbar-collapse -->
        </div>
    </nav>
{% endblock %}
<div class="container">
    {% block content %}{% endblock %}
</div>

<hr>

<footer>
    <p>&copy; Goaler 2017</p>
</footer>
</div> <!-- /container -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function (b, o, i, l, e, r) {
        b.GoogleAnalyticsObject = l;
        b[l] || (b[l] =
            function () {
                (b[l].q = b[l].q || []).push(arguments)
            });
        b[l].l = +new Date;
        e = o.createElement(i);
        r = o.getElementsByTagName(i)[0];
        e.src = 'http://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e, r)
    }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto');
    ga('send', 'pageview');
</script>
{% block footer_javascript %}{% endblock %}
</body>
</html>

goaler/templates/goaler/index.html
{% extends 'base.html' %}

{% load i18n %}
{% load l10n %}

{% block head_title %}Goaler{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>{% trans "Welcome to Goaler!" %}</h1>
            <p>{% blocktrans %}Log in to get tracking!{% endblocktrans %}<p>
        </div>
    </div>
{% endblock %}